# 左夹爪CAN总线配置

schema_version: 1

# CAN接口
interface: vcan6

# 总线上的关节
joints:

  # 左夹爪右指关节
  - name: gripper_left_right_finger_joint

    # 关节限制
    limits:
      # 最小位置(m)
      min_position: 0.001
      # 最大位置(m)
      max_position: 0.044
      # 最大速度(m/s)
      max_velocity: 0.04908738521234052

    # 电机配置
    motor:
      # CAN节点ID
      node_id: 8
      # 单位
      # radian: 旋转关节
      # meter: 直线关节
      unit: meter

      # 编码器参数
      encoder:
        # 每米对应编码器计数
        counts_per_meter: 651.8986469044033
        # 方向
        # 1 正向
        # -1 反向
        direction: 1
        # 零点偏移
        zero_offset: 0.0

  # 左夹爪左指关节
  - name: gripper_left_left_finger_joint

    # 关节限制
    limits:
      # 最小位置(m)
      min_position: 0.001
      # 最大位置(m)
      max_position: 0.044
      # 最大速度(m/s)
      max_velocity: 0.04908738521234052

    # 电机配置
    motor:
      # CAN节点ID
      node_id: 9
      # 单位
      unit: meter

      # 编码器参数
      encoder:
        # 每米对应编码器计数
        counts_per_meter: 651.8986469044033
        # 方向
        direction: 1
        # 零点偏移
        zero_offset: 0.0
