# 右肩CAN总线配置

schema_version: 1

# CAN接口
interface: vcan3

# 总线上的关节
joints:

  # 右肩第1关节
  - name: arm_right_1_joint

    # 关节限制
    limits:
      # 最小位置(rad)
      min_position: -1.1080972450961724
      # 最大位置(rad)
      max_position: 1.5007963267948966
      # 最大速度(rad/s)
      max_velocity: 0.17453292519943295

    # 电机配置
    motor:
      # CAN节点ID
      node_id: 17
      # 单位
      # radian: 旋转关节
      # meter: 直线关节
      unit: radian

      # 编码器参数
      encoder:
        # 电机每转编码器计数
        counts_per_motor_revolution: 4096
        # 减速比
        gear_ratio: 1.0
        # 方向
        # 1 正向
        # -1 反向
        direction: 1
        # 零点偏移
        zero_offset: 0.0

  # 右肩第2关节
  - name: arm_right_2_joint

    # 关节限制
    limits:
      # 最小位置(rad)
      min_position: -1.1080972450961724
      # 最大位置(rad)
      max_position: 1.5007963267948966
      # 最大速度(rad/s)
      max_velocity: 0.17453292519943295

    # 电机配置
    motor:
      # CAN节点ID
      node_id: 18
      # 单位
      unit: radian

      # 编码器参数
      encoder:
        # 电机每转编码器计数
        counts_per_motor_revolution: 4096
        # 减速比
        gear_ratio: 1.0
        # 方向
        direction: 1
        # 零点偏移
        zero_offset: 0.0
