# 右肘CAN总线配置

schema_version: 1

# CAN接口
interface: vcan4

# 总线上的关节
joints:

  # 右肘第1关节
  - name: arm_right_3_joint

    # 关节限制
    limits:
      # 最小位置(rad)
      min_position: -0.7153981633974483
      # 最大位置(rad)
      max_position: 3.8569908169872414
      # 最大速度(rad/s)
      max_velocity: 0.17453292519943295

    # 电机配置
    motor:
      # CAN节点ID
      node_id: 19
      # 单位
      # radian: 旋转关节
      # meter: 直线关节
      unit: radian

      # 编码器参数
      encoder:
        # 电机每转编码器计数
        counts_per_motor_revolution: 4096
        # 减速比
        gear_ratio: 1.0
        # 方向
        # 1 正向
        # -1 反向
        direction: 1
        # 零点偏移
        zero_offset: 0.0

  # 右肘第2关节
  - name: arm_right_4_joint

    # 关节限制
    limits:
      # 最小位置(rad)
      min_position: -0.32269908169872414
      # 最大位置(rad)
      max_position: 2.286194490192345
      # 最大速度(rad/s)
      max_velocity: 0.17453292519943295

    # 电机配置
    motor:
      # CAN节点ID
      node_id: 20
      # 单位
      unit: radian

      # 编码器参数
      encoder:
        # 电机每转编码器计数
        counts_per_motor_revolution: 4096
        # 减速比
        gear_ratio: 1.0
        # 方向
        direction: 1
        # 零点偏移
        zero_offset: 0.0
